/*******************************************************************************
 * Copyright 2012-2013 Trento RISE
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *        http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 ******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parchimetri.proto

package smartcampus.service.parchimetri.data.message;

public final class Parchimetri {
  private Parchimetri() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ParchimetroOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required double lat = 2;
    boolean hasLat();
    double getLat();
    
    // required double lon = 3;
    boolean hasLon();
    double getLon();
  }
  public static final class Parchimetro extends
      com.google.protobuf.GeneratedMessage
      implements ParchimetroOrBuilder {
    // Use Parchimetro.newBuilder() to construct.
    private Parchimetro(Builder builder) {
      super(builder);
    }
    private Parchimetro(boolean noInit) {}
    
    private static final Parchimetro defaultInstance;
    public static Parchimetro getDefaultInstance() {
      return defaultInstance;
    }
    
    public Parchimetro getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartcampus.service.parchimetri.data.message.Parchimetri.internal_static_smartcampus_service_parchimetri_data_message_Parchimetro_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartcampus.service.parchimetri.data.message.Parchimetri.internal_static_smartcampus_service_parchimetri_data_message_Parchimetro_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required double lat = 2;
    public static final int LAT_FIELD_NUMBER = 2;
    private double lat_;
    public boolean hasLat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getLat() {
      return lat_;
    }
    
    // required double lon = 3;
    public static final int LON_FIELD_NUMBER = 3;
    private double lon_;
    public boolean hasLon() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getLon() {
      return lon_;
    }
    
    private void initFields() {
      id_ = 0;
      lat_ = 0D;
      lon_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLon()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, lat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, lon_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, lon_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements smartcampus.service.parchimetri.data.message.Parchimetri.ParchimetroOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartcampus.service.parchimetri.data.message.Parchimetri.internal_static_smartcampus_service_parchimetri_data_message_Parchimetro_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartcampus.service.parchimetri.data.message.Parchimetri.internal_static_smartcampus_service_parchimetri_data_message_Parchimetro_fieldAccessorTable;
      }
      
      // Construct using smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        lon_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro.getDescriptor();
      }
      
      public smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro getDefaultInstanceForType() {
        return smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro.getDefaultInstance();
      }
      
      public smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro build() {
        smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro buildPartial() {
        smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro result = new smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lon_ = lon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro) {
          return mergeFrom((smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro other) {
        if (other == smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLon()) {
          setLon(other.getLon());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasLat()) {
          
          return false;
        }
        if (!hasLon()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              lat_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              lon_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required double lat = 2;
      private double lat_ ;
      public boolean hasLat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getLat() {
        return lat_;
      }
      public Builder setLat(double value) {
        bitField0_ |= 0x00000002;
        lat_ = value;
        onChanged();
        return this;
      }
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lat_ = 0D;
        onChanged();
        return this;
      }
      
      // required double lon = 3;
      private double lon_ ;
      public boolean hasLon() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getLon() {
        return lon_;
      }
      public Builder setLon(double value) {
        bitField0_ |= 0x00000004;
        lon_ = value;
        onChanged();
        return this;
      }
      public Builder clearLon() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lon_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:smartcampus.service.parchimetri.data.message.Parchimetro)
    }
    
    static {
      defaultInstance = new Parchimetro(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:smartcampus.service.parchimetri.data.message.Parchimetro)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_smartcampus_service_parchimetri_data_message_Parchimetro_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_smartcampus_service_parchimetri_data_message_Parchimetro_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021parchimetri.proto\022,smartcampus.service" +
      ".parchimetri.data.message\032\ncore.proto\"3\n" +
      "\013Parchimetro\022\n\n\002id\030\001 \002(\005\022\013\n\003lat\030\002 \002(\001\022\013\n" +
      "\003lon\030\003 \002(\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_smartcampus_service_parchimetri_data_message_Parchimetro_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_smartcampus_service_parchimetri_data_message_Parchimetro_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_smartcampus_service_parchimetri_data_message_Parchimetro_descriptor,
              new java.lang.String[] { "Id", "Lat", "Lon", },
              smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro.class,
              smartcampus.service.parchimetri.data.message.Parchimetri.Parchimetro.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          it.sayservice.platform.core.message.Core.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
